### ISSUE TITLE
Zotero has upgraded to a new ESR

### ISSUE THREAD

**Issue by retorquere** [ripefig/Firefox-ESR-52-Global-Menu#1]
Zotero has upgraded to a new ESR release. Will you be building a new libxul?

**Comment by ripefig** [comment]
I didn't build the original. That was @darthoctopus in https://github.com/zotero/zotero/issues/302

However, I got it working by downloading an old Thunderbird deb from Ubuntu, then extracting the `libxul.so` to the root `./` directory of zotero-bin, and all other shared libraries from the deb to a `./thunderbird` subfolder in the zotero directory. The only problem is an empty "Window" top-level menu which gets inserted into the menu hierarchy for some reason.

[This is where you can get the thunderbird 60.8.0 deb with the library files](https://launchpad.net/ubuntu/+source/thunderbird/1:60.8.0+build1-0ubuntu0.16.04.2).  An [earlier firefox 60.* build](https://launchpad.net/ubuntu/+source/firefox/60.0.2+build1-0ubuntu0.18.04.18) also works.

Unity menu patch can be found [here](http://bazaar.launchpad.net/~mozillateam/firefox/firefox-trunk.head/view/head:/debian/patches/unity-menubar.patch), if anyone is curious (not needed here, since everything is already compiled with the patch).


my `./zotero` launch script is modified as follows.

``` bash
ulimit -n 4096
CALLDIR="$(dirname "$(readlink -f "$0")")"

# point to the shared libraries required by Thunderbird's `libxul.so`:
LD_LIBRARY_PATH="$CALLDIR/thunderbird"
export LD_LIBRARY_PATH

"$CALLDIR/zotero-bin" -app "$CALLDIR/application.ini" "$@"

```
The last step is creating/editing `$HOME/.zotero/zotero/*****.default/userChrome.css` with the following code:

```css

window[shellshowingmenubar="true"] menubar {
  display: none !important;
}

window[shellshowingmenubar="true"]
toolbar[type="menubar"]:not([customizing="true"]) {
  min-height: 0 !important;
  border: 0 !important;
}

```
